CREATE SCHEMA vector_store;

SET search_path TO vector_store;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS ddl_collection (
	ID SERIAL PRIMARY KEY,
	DOCUMENT VARCHAR NOT NULL,
	QUESTION VARCHAR(500) NULL,
	EMBEDDING VECTOR(768)
);

CREATE INDEX IF NOT EXISTS ON DDL_COLLECTION USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS doc_collection (
	ID SERIAL PRIMARY KEY,
	DOCUMENT VARCHAR NOT NULL,
	QUESTION VARCHAR(500) NULL,
	EMBEDDING VECTOR(768)
);

CREATE INDEX IF NOT EXISTS ON DOC_COLLECTION USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS sql_collection (
	ID SERIAL PRIMARY KEY,
	DOCUMENT VARCHAR NOT NULL,
	QUESTION VARCHAR(500) NULL,
	EMBEDDING VECTOR(768)
);

CREATE INDEX IF NOT EXISTS ON SQL_COLLECTION USING hnsw (embedding vector_cosine_ops);